services:
  postal:
    image: 'ghcr.io/postalserver/postal:latest'
    container_name: postal
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - "./docker/ci-config:/config"
    environment:
      POSTAL_SIGNING_KEY_PATH: /config/signing.key
      MAIN_DB_HOST: mariadb
      MAIN_DB_USERNAME: root
      MESSAGE_DB_HOST: mariadb
      MESSAGE_DB_USERNAME: root
      LOGGING_ENABLED: "false"
      RAILS_ENVIRONMENT: test
      RAILS_LOG_ENABLED: "false"
      WAIT_FOR_TIMEOUT: 90
      WAIT_FOR_TARGETS: |-
        mariadb:3306
    ports:
      - "25:25"        # SMTP inbound
      - "587:587"      # SMTP submission
      - "2525:2525"    # Alternate SMTP port
      - "465:465"      # SMTPS
      - "5000:5000"    # Add this line: Postal web UI
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - coolify.managed=true
      - coolify.name=postal
      - coolify.serviceName=postal
      - traefik.enable=true
      - traefik.http.routers.postal.rule=Host(`postal.yourdomain.com`)
      - traefik.http.routers.postal.entrypoints=websecure
      - traefik.http.routers.postal.tls.certresolver=letsencrypt
      - traefik.http.services.postal.loadbalancer.server.port=5000
    networks:
      - coolify
      - postal-network
